# Generated by Django 5.2.16 on 2026-07-24 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0002_gateassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100, verbose_name='Passenger Name')),
                ('request_type', models.CharField(choices=[('WHEELCHAIR', 'Wheelchair Assistance'), ('LOST_FOUND', 'Lost and Found'), ('SPECIAL_ASSISTANCE', 'Special Assistance'), ('COMPLAINT', 'Complaint'), ('OTHER', 'Other')], max_length=30, verbose_name='Request Type')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='LOW', max_length=20, verbose_name='Priority')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_requests', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Staff')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_requests', to='flights.flight', verbose_name='Flight')),
            ],
            options={
                'verbose_name': 'Passenger Request',
                'verbose_name_plural': 'Passenger Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
