# Generated by Django 5.2.16 on 2026-08-07 12:33

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_actual_arrival_time_and_more'),
        ('passenger_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerrequest',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=30, verbose_name='Booking Reference'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='resolution_notes',
            field=models.TextField(blank=True, verbose_name='Resolution Notes'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='service_location',
            field=models.CharField(blank=True, max_length=150, verbose_name='Service Location'),
        ),
        migrations.AddField(
            model_name='passengerrequest',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Status Updated At'),
        ),
        migrations.AlterField(
            model_name='passengerrequest',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='LOW', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='passengerrequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='passengerrequest',
            index=models.Index(fields=['status', 'priority'], name='passenger_status_priority'),
        ),
        migrations.AddIndex(
            model_name='passengerrequest',
            index=models.Index(fields=['flight', 'status'], name='passenger_flight_status'),
        ),
        migrations.AddIndex(
            model_name='passengerrequest',
            index=models.Index(fields=['assigned_staff', 'status'], name='passenger_staff_status'),
        ),
    ]
