# Generated by Django 5.2.16 on 2026-07-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operators', to='airlines.airline', verbose_name='Airline'),
        ),
    ]
