# Generated by Django 5.2.16 on 2026-08-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'Operations Viewer'), ('ADMIN', 'Admin'), ('AIRPORT_MANAGER', 'Airport Manager'), ('AIRLINE_OPERATOR', 'Airline Operator'), ('GROUND_STAFF', 'Ground Staff'), ('SECURITY_OFFICER', 'Security Officer'), ('PASSENGER_SERVICE', 'Passenger Service')], default='VIEWER', max_length=30),
        ),
    ]
