# Generated by Django 5.2.16 on 2026-07-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Manufacturer')),
                ('model', models.CharField(max_length=100, verbose_name='Aircraft Model')),
                ('passenger_capacity', models.PositiveIntegerField(verbose_name='Passenger Capacity')),
                ('range_km', models.PositiveIntegerField(verbose_name='Range (KM)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aircraft Type',
                'verbose_name_plural': 'Aircraft Types',
                'ordering': ['manufacturer', 'model'],
            },
        ),
    ]
