# Generated by Django 5.2.16 on 2026-07-23 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Registration Number')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Serial Number')),
                ('manufacture_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Manufacture Year')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircrafts', to='fleet.aircrafttype', verbose_name='Aircraft Type')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircrafts', to='airlines.airline', verbose_name='Airline')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircrafts',
                'ordering': ['registration_number'],
            },
        ),
    ]
