# Generated by Django 5.2.16 on 2026-07-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircrafttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
