# Generated by Django 5.2.16 on 2026-07-23 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0003_gate'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_time', models.DateTimeField(auto_now_add=True, verbose_name='Assigned Time')),
                ('released_time', models.DateTimeField(blank=True, null=True, verbose_name='Released Time')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_assignments', to='flights.flight', verbose_name='Flight')),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='airports.gate', verbose_name='Gate')),
            ],
            options={
                'verbose_name': 'Gate Assignment',
                'verbose_name_plural': 'Gate Assignments',
                'ordering': ['-assigned_time'],
            },
        ),
    ]
