# Generated by Django 5.2.16 on 2026-08-05 04:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
        ('airports', '0003_gate'),
        ('fleet', '0003_aircrafttype_is_active'),
        ('flights', '0002_gateassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='actual_arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Arrival Time'),
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Departure Time'),
        ),
        migrations.AddField(
            model_name='flight',
            name='disruption_reason',
            field=models.TextField(blank=True, verbose_name='Delay or Cancellation Reason'),
        ),
        migrations.AddField(
            model_name='flight',
            name='estimated_arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated Arrival Time'),
        ),
        migrations.AddField(
            model_name='flight',
            name='estimated_departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estimated Departure Time'),
        ),
        migrations.AddField(
            model_name='flight',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Status Updated At'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['origin', 'departure_time', 'status'], name='flight_departure_board'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['destination', 'arrival_time', 'status'], name='flight_arrival_board'),
        ),
    ]
