# Generated by Django 5.2.16 on 2026-07-24 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0002_gateassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('PASSENGER', 'Passenger Issue'), ('BAGGAGE', 'Baggage Issue'), ('AIRCRAFT', 'Aircraft Security'), ('ACCESS', 'Access Control'), ('OTHER', 'Other')], max_length=20, verbose_name='Report Type')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20, verbose_name='Severity')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_reports', to='flights.flight', verbose_name='Flight')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_reports', to=settings.AUTH_USER_MODEL, verbose_name='Security Officer')),
            ],
            options={
                'verbose_name': 'Security Report',
                'verbose_name_plural': 'Security Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
