# Generated by Django 5.2.16 on 2026-08-07 10:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_actual_arrival_time_and_more'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securityreport',
            name='location',
            field=models.CharField(blank=True, max_length=150, verbose_name='Incident Location'),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='resolution_notes',
            field=models.TextField(blank=True, verbose_name='Resolution Notes'),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolved At'),
        ),
        migrations.AddField(
            model_name='securityreport',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Status Updated At'),
        ),
        migrations.AlterField(
            model_name='securityreport',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_reports', to=settings.AUTH_USER_MODEL, verbose_name='Security Officer'),
        ),
        migrations.AlterField(
            model_name='securityreport',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='securityreport',
            index=models.Index(fields=['status', 'severity'], name='security_status_severity'),
        ),
        migrations.AddIndex(
            model_name='securityreport',
            index=models.Index(fields=['flight', 'status'], name='security_flight_status'),
        ),
        migrations.AddIndex(
            model_name='securityreport',
            index=models.Index(fields=['officer', 'status'], name='security_officer_status'),
        ),
    ]
