# Generated by Django 5.2.16 on 2026-08-02 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('STATUS_CHANGE', 'Status Change'), ('ASSIGN', 'Assign'), ('RELEASE', 'Release'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], db_index=True, max_length=30)),
                ('entity_type', models.CharField(choices=[('FLIGHT', 'Flight'), ('GROUND_OPERATION', 'Ground Operation'), ('GATE_ASSIGNMENT', 'Gate Assignment')], db_index=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_entity_lookup'), models.Index(fields=['actor', 'created_at'], name='audit_actor_time')],
            },
        ),
    ]
