# Generated by Django 5.2.16 on 2026-07-23 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Gate Name')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Gate Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gates', to='airports.terminal', verbose_name='Terminal')),
            ],
            options={
                'verbose_name': 'Gate',
                'verbose_name_plural': 'Gates',
                'ordering': ['code'],
            },
        ),
    ]
