# Generated by Django 5.2.16 on 2026-07-23 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_operations', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Staff')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ground_operations', to='flights.flight', verbose_name='Flight')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='operations.operationtype', verbose_name='Operation Type')),
            ],
            options={
                'verbose_name': 'Ground Operation',
                'verbose_name_plural': 'Ground Operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
